<?php

/**
 * ComponentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComponentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComponentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Components');
    }
}