<?php

/**
 * ProductComponentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductComponentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductComponentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductComponents');
    }
}