<?php

/**
 * BaseComponents
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $component_id
 * @property string $name
 * @property Doctrine_Collection $ProductComponents
 * 
 * @method integer             getComponentId()       Returns the current record's "component_id" value
 * @method string              getName()              Returns the current record's "name" value
 * @method Doctrine_Collection getProductComponents() Returns the current record's "ProductComponents" collection
 * @method Components          setComponentId()       Sets the current record's "component_id" value
 * @method Components          setName()              Sets the current record's "name" value
 * @method Components          setProductComponents() Sets the current record's "ProductComponents" collection
 * 
 * @package    Achala
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComponents extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('components');
        $this->hasColumn('component_id', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 6,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProductComponents', array(
             'local' => 'component_id',
             'foreign' => 'component_id'));
    }
}