<?php

/**
 * BaseProductComponents
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $component_id
 * @property Products $Products
 * @property Components $Components
 * 
 * @method integer           getProductId()    Returns the current record's "product_id" value
 * @method integer           getComponentId()  Returns the current record's "component_id" value
 * @method Products          getProducts()     Returns the current record's "Products" value
 * @method Components        getComponents()   Returns the current record's "Components" value
 * @method ProductComponents setProductId()    Sets the current record's "product_id" value
 * @method ProductComponents setComponentId()  Sets the current record's "component_id" value
 * @method ProductComponents setProducts()     Sets the current record's "Products" value
 * @method ProductComponents setComponents()   Sets the current record's "Components" value
 * 
 * @package    Achala
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductComponents extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_components');
        $this->hasColumn('product_id', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 6,
             ));
        $this->hasColumn('component_id', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Products', array(
             'local' => 'product_id',
             'foreign' => 'product_id'));

        $this->hasOne('Components', array(
             'local' => 'component_id',
             'foreign' => 'component_id'));
    }
}